server:
  port: 9080

#security:
#  oauth2:
#    resource:
#      jwt:
#        # TokenKeyEndpoint 源码
#        key-uri: http://127.0.0.1:9090/oauth/token_key
#    client:
#      # 对应 oauth_client_details 的 orderService 的记录
#      client-id: orderService
#      client-secret: 123456

spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true  # 因为将来会引入很多依赖, 难免有重名的 bean
  cloud:
    nacos:
      # 服务注册发现
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: ${NACOS_ADDR:127.0.0.1}:8848
        namespace: ${NAMESPACE_ID:ded4d0b7-30c5-46b2-b2ac-08307547f712}
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator